Import('rtconfig')
from building import *

cwd = GetCurrentDir()
path = [cwd + '/', cwd + '/drivers']
src = Split('''
            system_MCXN236.c
            ''')

if rtconfig.PLATFORM in ['gcc']:
    src += ['gcc/startup_MCXN236.S']
elif rtconfig.PLATFORM in ['armcc', 'armclang']:
    src += ['arm/startup_MCXN236.S']
elif rtconfig.PLATFORM in ['iccarm']:
    src += ['iar/startup_MCXN236.s']

src += ['drivers/fsl_cache_lpcac.c']
src += ['drivers/fsl_cdog.c']
src += ['drivers/fsl_clock.c']
src += ['drivers/fsl_cmc.c']
src += ['drivers/fsl_common.c']
src += ['drivers/fsl_common_arm.c']
src += ['drivers/fsl_crc.c']
src += ['drivers/fsl_ctimer.c']
src += ['drivers/fsl_edma.c']
src += ['drivers/fsl_edma_soc.c']
src += ['drivers/fsl_eim.c']
src += ['drivers/fsl_erm.c']
src += ['drivers/fsl_evtg.c']
src += ['drivers/fsl_ewm.c']
src += ['drivers/fsl_flexcan.c']
src += ['drivers/fsl_flexcan_edma.c']
src += ['drivers/fsl_flexio.c']
src += ['drivers/fsl_flexio_i2c_master.c']
src += ['drivers/fsl_flexio_mculcd.c']
src += ['drivers/fsl_flexio_mculcd_edma.c']
src += ['drivers/fsl_flexio_spi.c']
src += ['drivers/fsl_flexio_spi_edma.c']
src += ['drivers/fsl_flexio_uart.c']
src += ['drivers/fsl_flexio_uart_edma.c']
src += ['drivers/fsl_freqme.c']
src += ['drivers/fsl_gpio.c']
src += ['drivers/fsl_i3c.c']
src += ['drivers/fsl_i3c_edma.c']
src += ['drivers/fsl_irtc.c']
src += ['drivers/fsl_lpadc.c']
src += ['drivers/fsl_lpflexcomm.c']
src += ['drivers/fsl_lpi2c.c']
src += ['drivers/fsl_lpi2c_edma.c']
src += ['drivers/fsl_lpspi.c']
src += ['drivers/fsl_lpspi_edma.c']
src += ['drivers/fsl_lptmr.c']
src += ['drivers/fsl_lpuart.c']
src += ['drivers/fsl_mrt.c']
src += ['drivers/fsl_wwdt.c']
src += ['drivers/fsl_reset.c']
src += ['drivers/fsl_spc.c']
src += ['drivers/fsl_vref.c']


group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path)

Return('group')
